### ISSUE TITLE
2017.1.20 总结

### ISSUE THREAD

**Issue by onetaste2016** [Xunlong2/operation#13]
![k 5m tizt h81h0rdv](https://cloud.githubusercontent.com/assets/24827881/22180582/035583ce-e0af-11e6-8a09-5d099d40241e.png)

![qq 20161228153203](https://cloud.githubusercontent.com/assets/24827881/22180586/094b359e-e0af-11e6-87b2-b4c865e16599.png)

![qq 20170103154420](https://cloud.githubusercontent.com/assets/24827881/22180587/12e372c4-e0af-11e6-9ba4-547a04399fd1.png)

中粮生化：早盘次新股大幅拉升，认为大盘会站稳反弹，中粮生化突破盘整平台准备拉升的时候买进。

![qq 20170103154625](https://cloud.githubusercontent.com/assets/24827881/22180594/21c3ab74-e0af-11e6-8c2e-64dec0dc8e60.png)
中金岭南：日线底部背驰，早盘站稳时候买进。

![qq 20170103161621](https://cloud.githubusercontent.com/assets/24827881/22180595/29220a0a-e0af-11e6-8499-a26f1fdc0a8f.png)
东方雨虹：日线底部背驰，相等回调买进，一直上涨，盘整后突破高点买进。

![qq 20170104163902](https://cloud.githubusercontent.com/assets/24827881/22180598/3451ec7e-e0af-11e6-8a69-233e9ae9653c.png)
晋西车轴：大盘二次确认顶部，晋西车轴跌破均价线的时候卖出。

![qq 20170103171834](https://cloud.githubusercontent.com/assets/24827881/22180596/31ef805e-e0af-11e6-8eeb-4c1a8c810a14.png)
中成股份：大盘二次确认顶部，中成股份盘整，二次确认顶部，认为上不去，卖出。

总结：
1.今天买进的三只股票都不够强势，都不是资金流进的主要板块，今天资金流进的板块是次新股、互联网等超跌的创业板。
2.早盘判断大盘会大幅上涨，果断满仓，尽管走不出想要的行情。
3.确认大盘会大幅上涨，东方雨虹应该及时的追进去，而不是等回调，在上涨行情中，越等待往往买进的价格越来越高，在上涨的行情中，要确保及时进场，而不是价格。

**Comment by gzMichael** [comment]
合并到同一天的[另外一篇总结](https://github.com/Xunlong2/operation/issues/12)中，此issue关闭。
